import moment from "moment";

const activities = [
  {
    title: "Explore Ubud A",
    category: "chill",
    type: "success",
    lengthTour: "2 Days, 1 night",
    date: moment().toISOString(),
    pict: "https://cdn.pixabay.com/photo/2017/04/26/11/02/quad-2262332_960_720.jpg",
    price: 150,
    link: "book-now/explore-ubud-a",
  },
  {
    title: "Explore Ubud B",
    category: "relax",
    type: "danger",
    lengthTour: "2 Days, 1 night",
    pict: "https://cdn.pixabay.com/photo/2018/06/30/00/13/tubing-3506869_1280.jpg",
    date: moment().toISOString(),
    price: 150,
    link: "book-now/explore-ubud-b",
  },
  {
    title: "Explore Ubud C",
    category: "chill",
    type: "success",
    lengthTour: "2 Days, 1 night",
    pict: "https://friendlybalitour.com/wp-content/uploads/2023/10/1698628237089.jpg",
    date: moment().toISOString(),
    price: 150,
    link: "book-now/explore-ubud-c",
  },
  {
    title: "Explore Ubud D",
    category: "chill",
    type: "success",
    lengthTour: "2 Days, 1 night",
    date: moment().toISOString(),
    pict: "https://cdn.pixabay.com/photo/2018/01/26/20/23/saber-3109719_960_720.jpg",
    price: 105,
    link: "book-now/explore-ubud-d",
  },
  {
    title: "Ubud Family Fun",
    category: "relax",
    type: "danger",
    lengthTour: "2 Days, 1 night",
    pict: "https://friendlybalitour.com/wp-content/uploads/2023/10/IMG_20231030_075214.jpg",
    date: moment().toISOString(),
    price: 110,
    link: "book-now/explore-family-fun",
  },
  {
    title: "Water Sport",
    category: "chill",
    type: "success",
    lengthTour: "2 Days, 1 night",
    pict: "https://friendlybalitour.com/wp-content/uploads/2023/10/1698645974707.jpg",
    date: moment().toISOString(),
    price: 105,
    link: "book-now/water-sport",
  },
];

export { activities };
